version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Adjust for your Python version
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r lambda_function.zip .
artifacts:
  files:
    - lambda_function.zip  # This is the packaged Lambda function
