AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3Bucket:
    Type: String
    Default: 'my-app-bucket-${AWS::AccountId}-${AWS::Region}'

Resources:
  
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaS3Policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:*'
                Resource: '*'

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'index.handler'  # Update based on your Lambda function entry point
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: 'S3EventLambdaFunction'
      Runtime: 'python3.9'  # Update based on your Lambda runtime
      Timeout: 60
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              print("Received event: " + json.dumps(event, indent=2))
              # Your Lambda logic here
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
  
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-app-bucket-${AWS::AccountId}-${AWS::Region}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"  # Trigger on file creation
            Function: !GetAtt LambdaFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: "suffix"
                    Value: ".csv"  # Optional: Trigger only for .csv files

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: 'Name of the S3 Bucket'

  LambdaFunctionName:
    Value: !Ref LambdaFunction
    Description: 'Lambda function name'
