Parameters:
  GitHubToken:
    Type: String
    NoEcho: true  # Ensures the token is not displayed in CloudFormation logs
    Description: "GitHub OAuth token to access the repository"

Resources:
  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "codebuild.amazonaws.com"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource: "*"
  
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: 'LambdaBuildProject'
      #Source:
      #  Type: 'CodePipeline'
      #  Location: 'SourceOutput'  # Refers to the artifact from CodePipeline Source stage
      Artifacts:
        Type: 'S3'
        Location: 'my-st-app-bucket-2025'
        Name: 'lambda-output'
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/python3.9'  # Or 'aws/codebuild/nodejs:14.x' depending on your Lambda runtime
        Type: 'LINUX_CONTAINER'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
  
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CodePipelineServiceRole'
      ArtifactStore:
        Type: S3
        Location: 'my-st-app-bucket-2025'
      Stages:
        - Name: 'Source'
          Actions:
            - Name: 'GitHub_Source'
              ActionTypeId:
                Category: 'Source'
                Owner: 'ThirdParty'
                Provider: 'GitHub'
                Version: '1'
              OutputArtifacts:
                - Name: 'SourceOutput'
              Configuration:
                Owner: 'STThukral'
                Repo: 'https://github.com/STThukral/github-to-aws'  # The name of the repository, not the full URL
                Branch: 'main'
                OAuthToken: !Ref GitHubToken
        - Name: 'Build'
          Actions:
            - Name: 'LambdaBuild'
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Provider: 'CodeBuild'
                Version: '1'
              InputArtifacts:
                - Name: 'SourceOutput'
              OutputArtifacts:
                - Name: 'BuildOutput'
              Configuration:
                ProjectName: !Ref 'CodeBuildProject'
        - Name: 'Deploy'
          Actions:
            - Name: 'CloudFormationDeploy'
              ActionTypeId:
                Category: 'Deploy'
                Owner: 'AWS'
                Provider: 'CloudFormation'
                Version: '1'
              InputArtifacts:
                - Name: 'SourceOutput'
              Configuration:
                ActionMode: 'CREATE_UPDATE'
                StackName: 'LambdaStack'
                TemplatePath: 'SourceOutput::lambda_buildspec_S3.yml'  # Correct reference to the CloudFormation template
                Capabilities: 'CAPABILITY_IAM'

  
