Parameters:
  GitHubToken:
    Type: String
    NoEcho: true  # Ensures the token is not displayed in CloudFormation logs
    Description: "GitHub OAuth token to access the repository"

Resources:
  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "codebuild.amazonaws.com"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DeleteStack"
                  - "iam:PassRole"
                Resource:
                  - "arn:aws:s3:::my-st-app-bucket-2025"
                  - "arn:aws:s3:::my-st-app-bucket-2025/*"
  
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:eu-west-2:277707117797:log-group:/aws/codebuild/*"
  
              - Effect: "Allow"
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource: "*"
  
  CodePipelineServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "codepipeline.amazonaws.com"
      Policies:
        - PolicyName: "CodePipelineServicePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "iam:PassRole"  # Important for passing roles to other services like CodeBuild
                Resource: "*"
  
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: 'LambdaBuildProject'
      Source:
        Type: 'GITHUB'
        Location: 'https://github.com/STThukral/github-to-aws'
      Artifacts:
        Type: 'S3'
        Location: 'my-st-app-bucket-2025'
        Name: 'lambda-output'
      Environment:
        ComputeType: 'BUILD_GENERAL1_MEDIUM'  # Updated compute type
        Image: 'aws/codebuild/standard:4.0'   # Image compatible with medium compute type
        Type: 'LINUX_CONTAINER'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
  
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn  # Ensure this references the correct role
      ArtifactStore:
        Type: S3
        Location: 'my-st-app-bucket-2025'
      Stages:
        - Name: 'Source'
          Actions:
            - Name: 'GitHub_Source'
              ActionTypeId:
                Category: 'Source'
                Owner: 'ThirdParty'
                Provider: 'GitHub'
                Version: '1'
              OutputArtifacts:
                - Name: 'SourceOutput'
              Configuration:
                Owner: 'STThukral'
                Repo: 'github-to-aws'  # The name of the repository, not the full URL
                Branch: 'main'
                OAuthToken: !Ref GitHubToken
        - Name: 'Build'
          Actions:
            - Name: 'LambdaBuild'
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Provider: 'CodeBuild'
                Version: '1'
              InputArtifacts:
                - Name: 'SourceOutput'
              OutputArtifacts:
                - Name: 'BuildOutput'
              Configuration:
                ProjectName: !Ref 'CodeBuildProject'
        - Name: 'Deploy'
          Actions:
            - Name: 'CloudFormationDeploy'
              ActionTypeId:
                Category: 'Deploy'
                Owner: 'AWS'
                Provider: 'CloudFormation'
                Version: '1'
              InputArtifacts:
                - Name: 'SourceOutput'
              Configuration:
                ActionMode: 'CREATE_UPDATE'
                StackName: 'LambdaStack'
                TemplatePath: 'SourceOutput::lambda_buildspec_S3.yml'  # Correct reference to the CloudFormation template
                Capabilities: 'CAPABILITY_IAM'

  
