name: Deploy Lambda to AWS via CodePipeline

on:
  push:
    branches:
      - main
    paths:
      - 'lambda-pipline-stack.yml'  # Trigger only when lambda-pipline-stack.yml is changed
      - 'lambda_buildspec_s3.yml'  # Trigger only  when lambda_buildspec_s3.yml is changed
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1

    - name: Start CodePipeline execution
      run: |
        aws codepipeline start-pipeline-execution --name lambda-pipeline-stack.yml
